# core tools
brew "vim"
brew "coreutils"
brew "stow"
brew "tree"
brew "bat"
brew "fzf"
brew "zoxide"
cask "visual-studio-code"
brew "jq"
brew "tlrc"
brew "btop"
brew "dua-cli"

# platform devtools
cask "docker"
brew "helm"
brew "minikube"

# languages
brew "node"
brew "pyenv"
brew "zlib"

# other tools
cask "background-music"
brew "imagemagick"
brew "img2pdf"
cask "maccy"
cask "rectangle"

