# core tools
brew "bat"
brew "btop"
brew "coreutils"
brew "git-delta"
brew "dua-cli"
brew "fzf"
brew "jq"
brew "ripgrep"
brew "stow"
brew "thefuck"
brew "tlrc"
brew "tree"
brew "neovim"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

tap "homebrew/cask-fonts"
cask "font-jetbrains-mono-nerd-font"

# platform devtools
cask "docker"

tap "jesseduffield/lazydocker"
brew "jesseduffield/lazydocker/lazydocker"

# languages
brew "node"
brew "pyenv"
brew "zlib"

# tools and apps
cask "firefox"
cask "iterm2"
cask "spotify"
cask "visual-studio-code"

cask "background-music"
brew "imagemagick"
brew "img2pdf"
cask "maccy"
cask "rectangle"
cask "the-unarchiver"

